{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "8d912da9",
   "metadata": {},
   "source": [
    "# Solve Me First\n",
    "\n",
    "> **Platform:** HackerRank  \n",
    "> **Difficulty:** Easy  \n",
    "> **Language:** C#\n",
    "\n",
    "---\n",
    "\n",
    "## 📖 Problem\n",
    "\n",
    "Given two integers `a` and `b`, return their sum.\n",
    "\n",
    "---\n",
    "\n",
    "## Idea\n",
    "\n",
    "The problem provides exactly **two integers**.\n",
    "\n",
    "Since the number of inputs is fixed, we don't need loops or advanced algorithms.\n",
    "\n",
    "The solution is simply to add the two numbers and return the result.\n",
    "\n",
    "---\n",
    "\n",
    "## Pattern\n",
    "\n",
    "### Direct Computation\n",
    "\n",
    "**Definition**\n",
    "\n",
    "Use this pattern when the problem requires performing an operation on a **fixed number of values**.\n",
    "\n",
    "### Characteristics\n",
    "\n",
    "- No loops.\n",
    "- No iteration.\n",
    "- No accumulation.\n",
    "- Constant execution time.\n",
    "\n",
    "### Common Use Cases\n",
    "\n",
    "- Add two numbers.\n",
    "- Subtract two numbers.\n",
    "- Compare two values.\n",
    "- Find the maximum/minimum of two values.\n",
    "\n",
    "---\n",
    "\n",
    "## Algorithm\n",
    "\n",
    "1. Receive the first integer.\n",
    "2. Receive the second integer.\n",
    "3. Compute their sum.\n",
    "4. Return the result.\n",
    "\n",
    "---\n",
    "\n",
    "## Complexity Analysis\n",
    "\n",
    "| Complexity | Value |\n",
    "|------------|-------|\n",
    "| **Time Complexity** | **O(1)** |\n",
    "| **Space Complexity** | **O(1)** |\n",
    "\n",
    "### Why?\n",
    "\n",
    "Only one addition operation is performed regardless of the input values.\n",
    "\n",
    "---\n",
    "\n",
    "## What I Learned\n",
    "\n",
    "- How to analyze a problem before writing code.\n",
    "- How to identify the **Input**, **Output**, and **Constraints**.\n",
    "- The difference between an **Algorithm** and its **Implementation**.\n",
    "- Constraints describe the expected input and do not necessarily require validation.\n",
    "- Introduced the **Direct Computation** pattern.\n",
    "\n",
    "---\n",
    "\n",
    "## Common Mistakes\n",
    "\n",
    "- Adding unnecessary input validation even though the problem doesn't require it.\n",
    "- Writing a complete Console Application instead of implementing only the required function.\n",
    "- Confusing **Algorithm** with **Implementation**.\n",
    "\n",
    "---\n",
    "\n",
    "## Key Takeaways\n",
    "\n",
    "- Always understand the problem before writing code.\n",
    "- Think about the algorithm first, then translate it into code.\n",
    "- Start with the simplest possible solution before looking for optimizations.\n",
    "\n",
    "---\n",
    "\n",
    "⭐ **Pattern Learned:** `Direct Computation`\n",
    "\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
